### ISSUE TITLE
version field issue in Fault and Measurement

### ISSUE THREAD

**Issue by miraj** [att/evel-library#13]
version fields of Fault and Measurement events is wrong.
 
"faultFieldsVersion": 1.1000000000000001,
"measurementsForVfScalingVersion": 1.1000000000000001,

it should be "1.1"

**Comment by PelagicGames** [comment]
I believe if you look at the JSON body of the HTTP POSTs sent by evel-library it will actually have the correct text (i.e. "1.1"), because evel_enc_version in `evel_json_buffer.c` encodes the integer `minor_version` using the `%d` format specifier.

The problem is likely that whatever is parsing the JSON correctly sees that it is a decimal number, and interprets it as such, but then due to floating point imprecision this becomes 1.1000000000000001. I noticed the same behaviour with the test collector, and it's possible to work around it by truncating the version length output by the test collector when printing field values.

Ideally the version fields would be strings, rather than numbers, but that's not what the specification calls for.

**Comment by miraj** [comment]
What you said is true. I used tcpdump to capture the event, and this is what I got.
 "measurementsForVfScalingVersion": 1.1

So closing the issue
