### ISSUE TITLE
VM Name , UUID read from metadata

### ISSUE THREAD

**Issue by patwardhan22** [att/evel-library#7]
Evel library reads UUID and VM name from metadata by default.
Can we assume in AT&T environment metadata is always available and these fields will be read correctly by evel library?
Or do we need to override these values in application by explicitly setting them ?

If Metadata is not available UUID and VM Name will be populated as below which does not look good
"Dummy VM UUID - No Metadata available"
"Dummy VM name - No Metadata available"

**Comment by PelagicGames** [comment]
The UUID and VM name come from Openstack metadata, and so will not necessarily be available for non-Openstack VMs.

Also, (at time of writing) the VM name may not be correct even for Openstack systems, because openstack_metadata only looks for the first instance of "name" in the metadata, but as the metadata is JSON and JSON is unordered the first instance may be in a nested JSON object, such as an SSH keypair.
